"use client";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/styles/Header";
import SVGDrible from "@/components/SVGS/SVGDrible";
import SVGLinkdin from "@/components/SVGS/SVGLinkdin";
import SVGMail from "@/components/SVGS/SVGMail";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased flex flex-col w-full relative min-h-screen gap-16`}
      >
        <Header />
        <main className=" container   min-h-screen flex-grow ">{children}</main>
        <div className="container h-36 flex items-center justify-center">
          <p className="text-sm font-light text-center flex flex-col items-center justify-center gap-4">
            <div className="flex gap-4">
              <div className="cursor-pointer p-2">
                <SVGMail />
              </div>
              <div className="cursor-pointer p-2">
                <SVGDrible />
              </div>
              <div className="cursor-pointer p-2">
                <SVGLinkdin />
              </div>
            </div>
            Looking forward to connecting with you!
          </p>
        </div>
      </body>
    </html>
  );
}
